name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: Erick-Dom
          svg_out_path: output/github-contribution-grid-snake.svg
          gif_out_path: output/github-contribution-grid-snake.gif
          color_snake: "#00ff00"               # cor da cobrinha (verde neon)
          color_dots: "#111111, #222222"       # tons dos quadradinhos
          background_color: "#000000"          # fundo preto

      - name: Commit e Push automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🐍 Atualizando animação da Snake"
